Lection 2 homework
mxwm/golang-basics pull request #2
Opened 2020-04-16 18:09 UTC by mxwm

2020-04-20 17:55 UTC, ikamornikau requested changes
Please address the requested changes.

2020-04-20 17:55 UTC, ikamornikau commented on homework3.go
> +	// function that returns the longest word from
Please see https://blog.golang.org/godoc and make appropriate changes.

2020-04-20 17:55 UTC, ikamornikau commented on homework3.go
> +	k := 0
What is `k`? Please rename.

2020-04-20 17:56 UTC, ikamornikau commented
BTW where is `printSorted()`?

2020-04-21 14:21 UTC, VolhaVetrava requested changes

2020-04-21 14:21 UTC, VolhaVetrava commented on homework3.go
> +	fmt.Println("In: ", arr, "len = ", len(arr), "cap = ", cap(arr))
`fmt.Printf` would look better here

2020-04-23 15:28 UTC, closed without merging